### ISSUE TITLE
Доработать страницы, обработаные скриптом

### ISSUE THREAD

**Issue by DzyubSpirit** [spometun/first_principles#3]
- [ ] mission.html
- [ ] cross.html
- [ ] best_friends_of_all_time.html
- [ ] church.html
- [ ] persecution.html
- [ ] miraculous_gifts_of_the_holy_spirit.html
- [ ] medical_account.html
- [ ] christ_is_your_life.html
- [ ] book_of_acts.html
- [ ] memory_scriptures.html
- [ ] after_baptism_now_what.html
- [ ] baptism_with_the_holy_spirit.html
- [ ] contact_us.html
- [ ] new_testament_conversion.html

**Comment by spometun** [comment]
Саня, пророби, будь-ласка, ці файли (всередині все має бути акуратно - немає крапок і пробілів в кінці, html має виглядати гарно (слова не зливаються, і т.д.)
Також звір, що весь текст рівно такий, як на usd21.org/m, де відрізняється, зроби як на usd21.org/m
